#Criando a tabela de colunas para as variáveis com a descrição e texto
tabelaColuna = {"Coluna":[    "TipoInstituicao",
                        "Regiao",
                        "Turno",
                        "EstadoCivil",
                        "Raca",
                        "EscolaridadePai",
                        "EscolaridadeMae",
                        "Moradia",
                        "RendaFamiliar",
                        "SituacaoFinanceira",
                        "Emprego",
                        "BolsaEstudos",
                        "InclusaoSocial",
                        "EscolaEnsinoMedio",
                        "ModalidadeEnsinoMedio",
                        "IncentivoGraduacao",
                        "Dificuldade",
                        "HoraEstudo",
                        "MotivoEscolha"
                ],
        
        "Descricao":[ "Tipo Instituição",
                        "Região",
                        "Turno",
                        "Estado Civil",
                        "Raça",
                        "Escolaridade do Pai",
                        "Escolaridade da Mãe",
                        "Tipo Moradia",
                        "Renda Familiar",
                        "Situação Financeira",
                        "Situação de Trabalho",
                        "Bolsa de Estudos",
                        "Inclusão Social",
                        "Tipo Escola Ensino Médio",
                        "Modalidade do Ensino Médio",
                        "Incentivo à Graduação",
                        "Ajuda na Dificuldade",
                        "Horas de Estudos",
                        "Motivo da Escolha"
                ],

        "Texto1":[     "Tipo de Instituição: pública ou privada",
                        "Região do país de funcionamento do curso",
                        "Turno da graduação",
                        "Estado civil do aluno",
                        "Raça declarada pelo aluno",
                        "Escolaridade concluída pelo pai",
                        "Escolaridade concluída pela mãe",
                        "Com quem o aluno reside atualmente",
                        "Renda total da família incluindo o rendimento do aluno",
                        "Situação financeira do aluno",
                        "Situação empregatícia do aluno",
                        "Bolsa de estudos ou financiamento",
                        "Políticas ou ações de inclusão social",
                        "Tipo de escola que o aluno cursou o seu ensino médio",
                        "Modalidade do ensino que o aluno concluiu o segundo grau",
                        "Quem mais incentivou o aluno a cursar a graduação",
                        "Quem foi quem mais ajudou o aluno durante a conclusão do curso superior",
                        "Horas dedicadas por semana aos estudos, excetuando as horas de aula",
                        "Principal motivo de ter escolhido o curso"
        ]
}